/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#717782",
        "on-surface": "#191c20",
        "on-secondary": "#ffffff",
        primary: "#005fa0",
        "on-secondary-container": "#005f7f",
        "on-primary-container": "#fdfcff",
        "primary-container": "#2578c0",
        "on-secondary-fixed": "#001e2b",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ee",
        "secondary-fixed-dim": "#88cff6",
        "secondary-fixed": "#c2e8ff",
        surface: "#f8f9ff",
        error: "#ba1a1a",
        "surface-variant": "#e0e2e9",
        "inverse-surface": "#2d3136",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-tertiary-container": "#fefcfb",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#1b1c1c",
        background: "#f8f9ff",
        "on-primary": "#ffffff",
        "secondary-container": "#90d8ff",
        "surface-container": "#eceef4",
        "primary-fixed-dim": "#9ecaff",
        "on-tertiary-fixed-variant": "#464747",
        "outline-variant": "#c1c7d2",
        secondary: "#026688",
        "on-tertiary": "#ffffff",
        tertiary: "#5c5c5c",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "surface-container-highest": "#e0e2e9",
        "on-secondary-fixed-variant": "#004d67",
        "surface-tint": "#0061a4",
        "surface-dim": "#d8dae0",
        "inverse-primary": "#9ecaff",
        "inverse-on-surface": "#eff0f7",
        "primary-fixed": "#d1e4ff",
        "tertiary-container": "#747474",
        "on-background": "#191c20",
        "surface-container-low": "#f2f3fa",
        "on-surface-variant": "#414751",
        "on-primary-fixed-variant": "#00497d",
        "tertiary-fixed": "#e3e2e2",
        "on-primary-fixed": "#001d36",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-padding-mobile": "48px",
        "section-padding-desktop": "80px",
        "container-max": "1200px",
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "label-bold": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        headline: ["Hanken Grotesk", "sans-serif"],
        display: ["Hanken Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [
    forms,
    containerQueries,
  ],
}
